"""add User-image

Revision ID: ac8995fdd201
Revises: d91db6505f5b
Create Date: 2017-04-16 19:43:18.646030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8995fdd201'
down_revision = 'd91db6505f5b'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    ### end Alembic commands ###
