"""add User-content

Revision ID: d91db6505f5b
Revises: fbbd7f885b36
Create Date: 2017-04-16 19:38:36.493864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91db6505f5b'
down_revision = 'fbbd7f885b36'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('content', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'content')
    ### end Alembic commands ###
